<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="product-options-bottom">
    <div class="product data items" id="asx">
        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#tab-order">One time order</a>
        </div>
        <div id="tab-order" class="item content" data-role="content"><?= $block->getChildHtml('product.info.addtocart', true) ?></div>
    </div>
</div>

<script>
    require([
        'jquery',
        'tabs'], function ($) {
        $("#asx").tabs();
    });
</script>
