<div class="discover-content">
    <div class="discover-list">
        <div class="discover-list__item">
            <p class="descovery-item-title">Brows</p>
            <a class="descovery-item-link" href="#">Discovery</a>
        </div>
    </div>
</div>


<div class="services-section">
    <div class="services-section-item">
    
        <p class="text">Free and Fast Shipping</p>
    </div>

    <div class="services-section-item">
        
        <p class="text">Cruelty-Free and Vegan</p>
    </div>

    <div class="services-section-item">
        
        <p class="text">Hassle-Free Returns</p>
    </div>
</div>

<div class="best-sellers">
    <div class="heading-title">
        <p class="title">Best Sellers</p>
    </div>

    <div class="instagram-content">
        
    </div>
</div>

<div class="footer-top">
    <div class="footer-top__content">
        <div class="footer-top__item recycle">
            <img src="" alt="">
            <p class="text">please recycle</p>
        </div>

        <div class="footer-top__item Owned">
            <img src="" alt="">
            <p class="text">Proudly Australian Owned</p>
        </div>

        <div class="footer-top__item recycle_2">
            <img src="" alt="">
            <p class="text">please recycle</p>
        </div>
    </div>
</div>

<div class="instagram-item">
    <a href="#"></a>
</div>

<div class="footer-middle">
    <div class="footer-middle-item need-help">
        <div class="title">
            <strong>Need help?</strong>
        </div>
        <div class="content">
            <ul class="menu">
                <li class="menu-item"></li>
            </ul>
        </div>

        <div class="need-help__below">
            <div class="bellow-content">
                <div class="blow-content__item proudly">
                    <img src="" alt="">
                    <p class="text">Proudly Australian Owned</p>
                </div>

                <div class="blow-content__item recycle">
                    <img src="" alt="">
                    <p class="text">Please Recycle</p>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-middle-item information">
        <div class="title">
            <strong>Information</strong>
        </div>
        <div class="content">
            <ul class="menu">
                <li class="menu-item"></li>
                <li class="menu-item"></li>
                <li class="menu-item"></li>
                <li class="menu-item"></li>
            </ul>
        </div>
    </div>

    <div class="footer-middle-item lip-heroes">
        <div class="title">
            <strong>Lip Heroes</strong>
        </div>
        <div class="content">
            <ul class="menu">
                <li class="menu-item"></li>
                <li class="menu-item"></li>
            </ul>
        </div>
    </div>
</div>

<div class="footer-bottom-cart">
    <div class="cart-content">
        <div class="cart-content__item">

        </div>

        <div class="cart-content__item">
            
        </div>

        <div class="cart-content__item">
        
        </div>

        <div class="cart-content__item">
        
        </div>
    </div>
</div>

